// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgzyPYo89Z154tZSM_RBjqBVNhWnXlboU',
    appId: '1:806678683521:web:4f64f43355ab0ce3cd1280',
    messagingSenderId: '806678683521',
    projectId: 'appointex-75143',
    authDomain: 'appointex-75143.firebaseapp.com',
    storageBucket: 'appointex-75143.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfmNYZM03a5G4wTmnCzNgkNCJM0-JRVt0',
    appId: '1:806678683521:android:a110d5236a83c347cd1280',
    messagingSenderId: '806678683521',
    projectId: 'appointex-75143',
    storageBucket: 'appointex-75143.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgXwmk4RW5Rh8cNUdNC3YZHCwlfTeoPz8',
    appId: '1:806678683521:ios:d17ced770e173ff8cd1280',
    messagingSenderId: '806678683521',
    projectId: 'appointex-75143',
    storageBucket: 'appointex-75143.firebasestorage.app',
    iosClientId: '806678683521-7j69vo6qg8a4j4g7gmi2fjtc3mji8bkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointex',
  );
}
