// GENERATED by tool/design/icons.mjs - do not edit by hand.
//
// Every glyph here was drawn by hand in the design. Do not substitute a Material
// or Lucide icon: see docs/05-ICON-CATALOG.md.

/// Monochrome UI icons. Tint with [AxIcon]'s `color`.
abstract final class AxIcons {
  /// 2 uses · Biz_Dashboard, Client_Home
  static const String bell = 'assets/icons/ui/bell.svg';

  /// 8 uses · Biz_Settings, Client_Book, Client_Checkout, Client_Home, Client_Urgent
  static const String boltFill = 'assets/icons/ui/bolt_fill.svg';

  /// 1 use · Main
  static const String briefcase = 'assets/icons/ui/briefcase.svg';

  /// 9 uses · Biz_Calendar, Biz_Clients, Biz_Dashboard, Biz_Earnings, Biz_FeaturedSpots, Biz_Services, Biz_Settings, Client_EventBundle, Client_Home
  static const String calendar = 'assets/icons/ui/calendar.svg';

  /// 1 use · Client_MyBookings
  static const String calendar22 = 'assets/icons/ui/calendar_22.svg';

  /// 7 uses · Biz_Calendar, Biz_Clients, Biz_Dashboard, Biz_Earnings, Biz_FeaturedSpots, Biz_Services, Biz_Settings
  static const String card = 'assets/icons/ui/card.svg';

  /// 2 uses · Client_Home, Client_Urgent
  static const String catHair = 'assets/icons/ui/cat_hair.svg';

  /// 2 uses · Client_Home, Client_Urgent
  static const String catMakeup = 'assets/icons/ui/cat_makeup.svg';

  /// 2 uses · Client_Home, Client_Urgent
  static const String catNails = 'assets/icons/ui/cat_nails.svg';

  /// 1 use · Client_Home
  static const String catPhotography = 'assets/icons/ui/cat_photography.svg';

  /// 2 uses · Client_Home, Client_Urgent
  static const String catSpa = 'assets/icons/ui/cat_spa.svg';

  /// 2 uses · Client_Home, Client_MyBookings
  static const String chat = 'assets/icons/ui/chat.svg';

  /// 3 uses · Client_EventBundle
  static const String check = 'assets/icons/ui/check.svg';

  /// 1 use · Client_Provider
  static const String checkBold = 'assets/icons/ui/check_bold.svg';

  /// 1 use · Client_Confirmation
  static const String checkCircle24 = 'assets/icons/ui/check_circle_24.svg';

  /// 2 uses · Biz_Onboarding, Client_Home
  static const String chevronDown = 'assets/icons/ui/chevron_down.svg';

  /// 8 uses · Biz_Calendar, Client_Book, Client_Chat, Client_Checkout, Client_EventBundle, Client_Register, Client_Search, Client_Urgent
  static const String chevronLeft = 'assets/icons/ui/chevron_left.svg';

  /// 1 use · Client_Book
  static const String chevronLeft23 = 'assets/icons/ui/chevron_left_23.svg';

  /// 1 use · Client_Provider
  static const String chevronLeft24 = 'assets/icons/ui/chevron_left_24.svg';

  /// 1 use · Biz_Calendar
  static const String chevronRight = 'assets/icons/ui/chevron_right.svg';

  /// 1 use · Client_Book
  static const String chevronRight23 = 'assets/icons/ui/chevron_right_23.svg';

  /// 1 use · Client_Home
  static const String chevronRight25 = 'assets/icons/ui/chevron_right_25.svg';

  /// 1 use · Client_Urgent
  static const String clock = 'assets/icons/ui/clock.svg';

  /// 1 use · Client_Register
  static const String eye = 'assets/icons/ui/eye.svg';

  /// 1 use · Client_Search
  static const String filter = 'assets/icons/ui/filter.svg';

  /// 7 uses · Biz_Calendar, Biz_Clients, Biz_Dashboard, Biz_Earnings, Biz_FeaturedSpots, Biz_Services, Biz_Settings
  static const String grid = 'assets/icons/ui/grid.svg';

  /// 1 use · Client_Home
  static const String home = 'assets/icons/ui/home.svg';

  /// 1 use · Client_MyBookings
  static const String home20 = 'assets/icons/ui/home_20.svg';

  /// 1 use · Biz_Onboarding
  static const String image = 'assets/icons/ui/image.svg';

  /// 7 uses · Biz_Calendar, Biz_Clients, Biz_Dashboard, Biz_Earnings, Biz_FeaturedSpots, Biz_Services, Biz_Settings
  static const String list = 'assets/icons/ui/list.svg';

  /// 1 use · Client_Chat
  static const String lock = 'assets/icons/ui/lock.svg';

  /// 1 use · Client_Chat
  static const String lock24 = 'assets/icons/ui/lock_24.svg';

  /// 1 use · Client_Checkout
  static const String lock20 = 'assets/icons/ui/lock_20.svg';

  /// 1 use · Biz_Settings
  static const String mapPin23 = 'assets/icons/ui/map_pin_23.svg';

  /// 1 use · Client_Book
  static const String mapPin20 = 'assets/icons/ui/map_pin_20.svg';

  /// 1 use · Client_Book
  static const String mapPin24 = 'assets/icons/ui/map_pin_24.svg';

  /// 2 uses · Client_Checkout, Client_Provider
  static const String mapPin = 'assets/icons/ui/map_pin.svg';

  /// 1 use · Client_Checkout
  static const String mapPin26 = 'assets/icons/ui/map_pin_26.svg';

  /// 8 uses · Biz_Clients, Biz_Settings, Client_Chat
  static const String personFill = 'assets/icons/ui/person_fill.svg';

  /// 1 use · Client_Provider
  static const String playFill = 'assets/icons/ui/play_fill.svg';

  /// 1 use · Client_EventBundle
  static const String plus24 = 'assets/icons/ui/plus_24.svg';

  /// 3 uses · Client_Provider
  static const String plus = 'assets/icons/ui/plus.svg';

  /// 1 use · Biz_Clients
  static const String search = 'assets/icons/ui/search.svg';

  /// 1 use · Client_Home
  static const String search20 = 'assets/icons/ui/search_20.svg';

  /// 1 use · Client_Chat
  static const String send = 'assets/icons/ui/send.svg';

  /// 7 uses · Biz_Calendar, Biz_Clients, Biz_Dashboard, Biz_Earnings, Biz_FeaturedSpots, Biz_Services, Biz_Settings
  static const String settings = 'assets/icons/ui/settings.svg';

  /// 1 use · Client_Checkout
  static const String shield = 'assets/icons/ui/shield.svg';

  /// 1 use · Client_Provider
  static const String shield22 = 'assets/icons/ui/shield_22.svg';

  /// 11 uses · Biz_Dashboard, Client_Home, Client_Provider, Client_Search
  static const String starFill = 'assets/icons/ui/star_fill.svg';

  /// 8 uses · Biz_Calendar, Biz_Clients, Biz_Dashboard, Biz_Earnings, Biz_FeaturedSpots, Biz_Services, Biz_Settings
  static const String starOutline = 'assets/icons/ui/star_outline.svg';

  /// 1 use · Client_Book
  static const String store = 'assets/icons/ui/store.svg';

  /// 9 uses · Biz_Calendar, Biz_Clients, Biz_Dashboard, Biz_Earnings, Biz_FeaturedSpots, Biz_Services, Biz_Settings, Client_Home, Client_MyBookings
  static const String user = 'assets/icons/ui/user.svg';
}

/// Two-tone UI icons. They carry their own colours (the verified badge's white
/// tick, the logo's peach centre), so tinting them destroys them. Render with
/// [AxDuoIcon], which exposes no `color`.
abstract final class AxDuoIcons {
  /// 8 uses · Client_Home, Client_Provider, Client_Search, Client_Urgent
  static const String checkCircle = 'assets/icons/duo/check_circle.svg';

  /// 10 uses · Biz_Calendar, Biz_Clients, Biz_Dashboard, Biz_Earnings, Biz_FeaturedSpots, Biz_Onboarding, Biz_Services, Biz_Settings, Client_Onboarding, Main
  static const String logoMark = 'assets/icons/duo/logo_mark.svg';
}

/// Illustrative art used inside [AxAvatar]. These carry their own colours and
/// must never be tinted.
abstract final class AxArt {
  /// 3 uses · Client_EventBundle, Client_Home
  static const String artBraids = 'assets/icons/art/art_braids.svg';

  /// 8 uses · Biz_FeaturedSpots, Biz_Settings, Client_EventBundle, Client_Home, Client_Provider, Client_Search, Client_Urgent
  static const String artMakeup = 'assets/icons/art/art_makeup.svg';

  /// 5 uses · Biz_FeaturedSpots, Client_Provider, Client_Search, Client_Urgent
  static const String artNails = 'assets/icons/art/art_nails.svg';

  /// 1 use · Client_Provider
  static const String artPerson = 'assets/icons/art/art_person.svg';

  /// 1 use · Client_EventBundle
  static const String artPhotography = 'assets/icons/art/art_photography.svg';

  /// 4 uses · Biz_FeaturedSpots, Client_Provider, Client_Search
  static const String artSpa = 'assets/icons/art/art_spa.svg';
}
